version: '3.8'

services:
  web:
    build: .
    command: uvicorn core.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - TZ=Asia/Bishkek
      - POSTGRES_USER=bet
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bet_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  .:
  postgres_data:
