"""bet model

Revision ID: 8bc00ba7c6ea
Revises: 12e45efb2ad2
Create Date: 2024-03-15 01:00:11.698704+06:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc00ba7c6ea'
down_revision: Union[str, None] = '12e45efb2ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps_bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_identifier', sa.String(length=50), nullable=True),
    sa.Column('bet_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('not_played', 'won', 'lost', name='betstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apps_bets_id'), 'apps_bets', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apps_bets_id'), table_name='apps_bets')
    op.drop_table('apps_bets')
    # ### end Alembic commands ###
